"""
report_generator.py
====================
Synthesizes the final structured research report (section 8/19) using the
"synthesis" provider, then renders it into every export format the app
supports: Markdown, HTML, PDF, TXT, and JSON (section 20).

Sources and detected conflicts are NOT re-generated by the AI at this
stage - they come straight from the database (real, previously-collected
data) so the report can never cite a source the agent didn't actually find.
"""
from __future__ import annotations

import io
import json
import logging
from datetime import datetime, timezone

import markdown as md_lib
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from provider_router import ProviderRouter
from schemas import FinalReport

logger = logging.getLogger("insightforge.report")

SYNTHESIS_SYSTEM_PROMPT = (
    "You are the synthesis module of InsightForge AI. You write the analytical "
    "content of a professional research report based on task summaries collected "
    "during a multi-step research process. You are precise, avoid unsupported "
    "claims, and clearly note where evidence is thin. Always respond with valid "
    "JSON only."
)

SYNTHESIS_SCHEMA_HINT = """{
  "title": "<concise report title>",
  "executive_summary": "<2-4 sentence high-level summary>",
  "methodology": "<one paragraph describing how the research was conducted>",
  "key_findings": ["<finding 1>", "<finding 2>", "..."],
  "detailed_analysis": "<several paragraphs of in-depth analysis, may use markdown>",
  "comparison": "<comparison of options/entities discussed, if applicable, else empty string>",
  "limitations": ["<limitation 1>", "..."],
  "conclusion": "<concluding paragraph>"
}"""


async def synthesize_report(
    router: ProviderRouter,
    *,
    research_question: str,
    task_results: list[dict],
    sources: list[dict],
    conflicts: list[dict],
    mode: str,
    usage_recorder=None,
) -> FinalReport:
    task_block = "\n\n".join(
        f"Task: {t['title']}\nFindings: {t.get('result_summary', 'No findings recorded.')}" for t in task_results
    )
    conflict_note = (
        f"\n\n{len(conflicts)} factual conflict(s) were detected between sources during cross-checking; "
        "acknowledge this in the report where relevant."
        if conflicts
        else ""
    )
    user_prompt = (
        f'Research question: "{research_question}"\n'
        f"Research depth: {mode}\n"
        f"Sources collected: {len(sources)}\n\n"
        f"Task findings:\n{task_block}{conflict_note}\n\n"
        "Write the analytical sections of the final research report."
    )

    result = await router.run_structured(
        stage="synthesis",
        system_prompt=SYNTHESIS_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        schema_hint=SYNTHESIS_SCHEMA_HINT,
        max_tokens=3000,
        temperature=0.35,
        usage_recorder=usage_recorder,
    )

    data = result.raw_json or {}
    data.setdefault("title", f"Research Report: {research_question[:100]}")
    data.setdefault("research_question", research_question)
    data["sources"] = sources
    data["conflicting_information"] = conflicts

    try:
        return FinalReport.model_validate(data)
    except Exception as exc:  # noqa: BLE001
        logger.warning("synthesis output failed validation, using safe fallback: %s", exc)
        return FinalReport(
            title=str(data.get("title", "Research Report")),
            executive_summary=str(data.get("executive_summary", "")) or "See detailed analysis below.",
            research_question=research_question,
            methodology=str(data.get("methodology", "")),
            key_findings=[str(f) for f in data.get("key_findings", []) if isinstance(f, (str, int, float))],
            detailed_analysis=str(data.get("detailed_analysis", "")),
            comparison=str(data.get("comparison", "")),
            conflicting_information=[c if isinstance(c, dict) else {} for c in conflicts],
            limitations=[str(l) for l in data.get("limitations", [])],
            conclusion=str(data.get("conclusion", "")),
            sources=sources,
        )


# ----------------------------------------------------------------------------
# Export renderers
# ----------------------------------------------------------------------------
def to_dict(report: FinalReport) -> dict:
    return report.model_dump()


def to_json(report: FinalReport) -> str:
    return json.dumps(to_dict(report), indent=2, default=str)


def to_markdown(report: FinalReport) -> str:
    lines = [f"# {report.title}", ""]
    lines += ["## Executive Summary", "", report.executive_summary, ""]
    if report.research_question:
        lines += ["## Research Question", "", report.research_question, ""]
    if report.methodology:
        lines += ["## Methodology", "", report.methodology, ""]
    if report.key_findings:
        lines += ["## Key Findings", ""]
        lines += [f"- {f}" for f in report.key_findings]
        lines.append("")
    if report.detailed_analysis:
        lines += ["## Detailed Analysis", "", report.detailed_analysis, ""]
    if report.comparison:
        lines += ["## Comparison", "", report.comparison, ""]
    if report.conflicting_information:
        lines += ["## Conflicting Information", ""]
        for c in report.conflicting_information:
            lines.append(
                f"- **{c.topic}**: {c.description}\n"
                f"  - {c.source_a_title}: {c.source_a_value}\n"
                f"  - {c.source_b_title}: {c.source_b_value}"
            )
        lines.append("")
    if report.limitations:
        lines += ["## Limitations", ""]
        lines += [f"- {l}" for l in report.limitations]
        lines.append("")
    if report.conclusion:
        lines += ["## Conclusion", "", report.conclusion, ""]
    if report.sources:
        lines += ["## Sources", ""]
        for i, s in enumerate(report.sources, start=1):
            lines.append(f"{i}. [{s.title}]({s.url}) - {s.source or s.url}")
        lines.append("")
    lines.append(f"\n---\n*Generated by InsightForge AI on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")
    return "\n".join(lines)


def to_html(report: FinalReport) -> str:
    body = md_lib.markdown(to_markdown(report), extensions=["tables", "fenced_code"])
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{report.title}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; max-width: 860px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #1a1a2e; }}
  h1 {{ border-bottom: 3px solid #4f46e5; padding-bottom: 12px; }}
  h2 {{ color: #4f46e5; margin-top: 32px; }}
  a {{ color: #4f46e5; }}
  ul {{ padding-left: 22px; }}
</style>
</head>
<body>
{body}
</body>
</html>"""


def to_txt(report: FinalReport) -> str:
    import re

    md = to_markdown(report)
    text = re.sub(r"[#*_`]|\[|\]\([^)]*\)", "", md)
    return text


def to_pdf(report: FinalReport) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], textColor=colors.HexColor("#4f46e5"))
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#4f46e5"), spaceBefore=14)
    body_style = styles["BodyText"]

    story = [Paragraph(report.title, title_style), Spacer(1, 14)]

    def section(heading: str, content: str) -> None:
        if not content:
            return
        story.append(Paragraph(heading, h2_style))
        for para in content.split("\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), body_style))
        story.append(Spacer(1, 6))

    section("Executive Summary", report.executive_summary)
    section("Methodology", report.methodology)

    if report.key_findings:
        story.append(Paragraph("Key Findings", h2_style))
        story.append(ListFlowable([ListItem(Paragraph(f, body_style)) for f in report.key_findings], bulletType="bullet"))
        story.append(Spacer(1, 6))

    section("Detailed Analysis", report.detailed_analysis)
    section("Comparison", report.comparison)

    if report.conflicting_information:
        story.append(Paragraph("Conflicting Information", h2_style))
        data = [["Topic", "Source A", "Source B"]]
        for c in report.conflicting_information:
            data.append([c.topic, f"{c.source_a_title}: {c.source_a_value}", f"{c.source_b_title}: {c.source_b_value}"])
        table = Table(data, colWidths=[1.5 * inch, 2.5 * inch, 2.5 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 6))

    if report.limitations:
        story.append(Paragraph("Limitations", h2_style))
        story.append(ListFlowable([ListItem(Paragraph(l, body_style)) for l in report.limitations], bulletType="bullet"))
        story.append(Spacer(1, 6))

    section("Conclusion", report.conclusion)

    if report.sources:
        story.append(Paragraph("Sources", h2_style))
        for i, s in enumerate(report.sources, start=1):
            story.append(Paragraph(f"{i}. {s.title} - <link href='{s.url}'>{s.url}</link>", body_style))

    doc.build(story)
    return buffer.getvalue()


EXPORTERS = {
    "markdown": to_markdown,
    "html": to_html,
    "txt": to_txt,
    "json": to_json,
    "pdf": to_pdf,
}
